import type { Monster } from "../entities/Monster";
import { Creature } from "../enums/Creature";
import { Rarity } from "../enums/Rarity";
import { Type } from "../enums/Type";
import { beakDance, flamethrower, frostPunch, vineSlap } from "./MovesDatabase";
import { regenBoost, revengeFurry } from "./PassiveSkillDatabase";

export const MonsterDatabase: Record<string, Monster> = {
    
    "0001": {
        id: "0001",
        speciesID: "🐒",
        rarity: Rarity.RARE,
        name: "Rimeape",
        creature: Creature.MONKEY,
        type: Type.ICE,
        // move: ,
        hp: 100,
        attack: 80,
        defense: 45,
        speed: 90,
        accuracy: 0,
        evasion: 0,
        move: frostPunch,
        passives: []
    },
    "0002": {
        id: "0002",
        speciesID: "🐼",
        rarity: Rarity.RARE,
        name: "Bambeast",
        creature: Creature.PANDA,
        type: Type.GRASS,
        // move: ,
        hp: 120,
        attack: 70,
        defense: 60,
        speed: 55,
        accuracy: 0,
        evasion: 0,
        move: vineSlap,
        passives: []
    },
    "0003": {
        id: "0003",
        speciesID: "🕊️",
        rarity: Rarity.RARE,
        name: "Whifdraft",
        creature: Creature.BIRD,
        type: Type.FLYING,
        // move: ,
        hp: 90,
        attack: 70,
        defense: 55,
        speed: 75,
        accuracy: 0,
        evasion: 0,
        move: beakDance,
        passives: []
    },
    "0004": {
        id: "0004",
        speciesID: "🐜",
        rarity: Rarity.COMMON,
        name: "Flarant",
        creature: Creature.ANT,
        type: Type.FIRE,
        // move: ,
        hp: 60,
        attack: 70,
        defense: 55,
        speed: 75,
        accuracy: 0,
        evasion: 0,
        move: flamethrower,
        passives: []
    },

    "0005": {
        id: "0005",
        speciesID: "🐘",
        rarity: Rarity.COMMON,
        name: "Elegiphant",
        creature: Creature.ELEPHANT,
        type: Type.WATER,
        hp: 120,
        attack: 50,
        defense: 80,
        speed: 40,
        accuracy: 0,
        evasion: 0,
        move: null,
        passives: []
    },

    "0006": {
        id: "0006",
        speciesID: "🌿",
        rarity: Rarity.COMMON,
        name: "Plantrum",
        creature: Creature.PLANT,
        type: Type.GRASS,
        hp: 100,
        attack: 40,
        defense: 30,
        speed: 55,
        accuracy: 0,
        evasion: 0,
        move: null,
        passives: []
    },

    "0007": {
        id: "0007",
        speciesID: "🐛",
        rarity: Rarity.UNCOMMON,
        name: "Caterpule",
        creature: Creature.CATERPILLAR,
        type: Type.BUG,
        hp: 90,
        attack: 40,
        defense: 40,
        speed: 70,
        accuracy: 0,
        evasion: 0,
        move: null,
        passives: [],
      },

      "0008": {
        id: "0008",
        speciesID: "⚡️",
        rarity: Rarity.RARE,
        name: "Voltrab",
        creature: Creature.RABBIT,
        type: Type.ELECTRIC,
        hp: 80,
        attack: 65,
        defense: 50,
        speed: 90,
        accuracy: 0,
        evasion: 0,
        move: null,
        passives: [],
      },

      "0009": {
        id: "0009",
        speciesID: "🐧",
        rarity: Rarity.RARE,
        name: "Iglio",
        creature: Creature.PENGUIN,
        type: Type.ICE,
        hp: 120,
        attack: 45,
        defense: 100,
        speed: 60,
        accuracy: 0,
        evasion: 0,
        move: null,
        passives: [],
      },

      "0010": {
        id: "0010",
        speciesID: "👻",
        rarity: Rarity.ULTRARARE,
        name: "Spectrium",
        creature: Creature.GHOST,
        type: Type.GHOST,
        hp: 100,
        attack: 45,
        defense: 90,
        speed: 80,
        accuracy: 0,
        evasion: 0,
        move: null,
        passives: [],
      },

      "0011": {
        id: "0011",
        speciesID: "🐲",
        rarity: Rarity.LEGENDARY,
        name: "Korigon",
        creature: Creature.DRAGON,
        type: Type.ICE,
        hp: 180,
        attack: 110,
        defense: 150,
        speed: 90,
        accuracy: 0,
        evasion: 0,
        move: null,
        passives: [],
      },

      "0012": {
        id: "0012",
        speciesID: "🐲",
        rarity: Rarity.LEGENDARY,
        name: "Infernados",
        creature: Creature.DRAGON,
        type: Type.FIRE,
        hp: 150,
        attack: 120,
        defense: 100,
        speed: 90,
        accuracy: 0,
        evasion: 0,
        move: null,
        passives: [],
      }

      
}

